version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_DATABASE: 'demo'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'demo_user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'demo_pass'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
  appproducer:
    build: .
    depends_on:
      - zookeeper
      - kafka
      - db
    ports:
      - "8080:8080" 
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/demo?useSSL=false
  logsconsumer:
    build: ./my-consumer-logs
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  myconsumer:
    build: ./my-consumer
    depends_on:
      - kafka
    ports:
      - "8082:8082"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  react:
    build: ./weather-front-end
    depends_on:
      - appproducer
    volumes: 
      - '.:/app'
      - '/app/node_modules'
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true